Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# TODO: enable
Metrics/ParameterLists:
  Enabled: false

