name: Style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install git libfontconfig1-dev libsndfile1-dev libsdl2-dev libmpg123-dev libopenal1 libopenal-dev shellcheck
        gem install bundler
        gem install rubocop:1.31.2
        bundle install --jobs 4 --retry 3
    - name: Check ruby with rubocop
      run: |
        rubocop
    - name: Shellcheck
      run: find . -type f -name '*.sh' -print0 | xargs -0 shellcheck
